### ISSUE TITLE
百灵鸟app真机测试无法连接server

### ISSUE THREAD

**Issue by xingweitian** [vczero/React-Native-App#10]
老师您好，请问真机和电脑在同一个Wi-Fi下，AppDelegate.m也已经修改成本机的地址。但是真机一直无法连接server文件夹下运行的app.js，请问如何解决？麻烦您了！

**Comment by vczero** [comment]
你需要打开自己电脑的防火墙，实在不行可以启动80端口，这个需要改3个地方：（1）app.js  (2)react native 代码下面的views/service.js (3)AppDelegate.m 中js地址

**Comment by xingweitian** [comment]
我把service.js中的地址修改为本机地址，成功连接server。感谢老师！
