### ISSUE TITLE
Android中有没有类似TabBarIOS的组件

### ISSUE THREAD

**Issue by codingEcho** [vczero/React-Native-App#12]
最近刚学习RN,但是Android似乎发育的不太健全，好多组件不如IOS。使用了TabNavigator，但是结果不太理想，有没有替代的组件推荐呢。

**Comment by vczero** [comment]
这个其实不同平台的组件，iOS和Android是不同的，比如菜单是TabBar和抽屉。

**Comment by Chaunjie** [comment]
@vczero TabBarIOS如何在一些二级页面做隐藏呢

**Comment by vczero** [comment]
@codingEcho  https://github.com/exponentjs/react-native-tab-navigator

**Comment by Chaunjie** [comment]
@vczero 谢谢

**Comment by vczero** [comment]
@codingEcho  https://github.com/exponentjs/react-native-tab-navigator ？
@xudao520 https://github.com/facebook/react-native/issues/1489 这个上面有一些方案
http://www.appcoda.com/ios-programming-101-how-to-hide-tab-bar-navigation-controller/

**Comment by codingEcho** [comment]
@vczero 对就是这个，tab和navigator这里对初学者来说不太容易

**Comment by MrVokie** [comment]
learn once, write anywhere.    T-T
