### ISSUE TITLE
通讯录App  总是提示用户名或密码错误

### ISSUE THREAD

**Issue by SeanWit** [vczero/React-Native-App#3]
使用作者提供的初次登录用户名:test@126.com    密码：123 进行登陆测试，总是提示用户名或密码错误，这是这么回事呢？

**Comment by SeanWit** [comment]
已解决 账户名应该是  test0@126.com

**Comment by vczero** [comment]
多谢！ok，已经是被我删除了。可以查看server/database/user.json文件。里面存储的用户信息。但是建议不要手动修改。
