### ISSUE TITLE
切换界面为什么很慢？

### ISSUE THREAD

**Issue by batulu12** [vczero/React-Native-App#5]

**Comment by vczero** [comment]
请提供测试的case，我来看看。ps: 总体上切换页面的确没有原生快。

**Comment by yuanjianhang** [comment]
模拟器的菜单栏，
查看下“debug － Slow Animation”是否勾选。

**Comment by yuanjianhang** [comment]
模拟器的菜单栏，
查看下“debug － Slow Animation”是否勾选。 @batulu12

**Comment by vczero** [comment]
@batulu12 Navigator组件的确存在这样的问题，目前NavigatorIOS组件做了不少改进，应该可以满足你基本需求。
