### ISSUE TITLE
Warning : Failed propType

### ISSUE THREAD

**Issue by xingweitian** [vczero/React-Native-App#8]
王老师您好，我最近在学习您的新书《React Native入门与实战》
在企业内部通讯录那一课中，我在写完登陆界面，用xcode运行的时候，会提示我一个warning

Warning: Failed propType: Invalid prop 'initialRoute.component' of type 'object' supplied to 'NavigatorIOS', expected 'function' . Check the render method of 'myapp' .

请问这是什么引起的错误？下面为_addNavigator的代码，与您的一致。

_addNavigator: function(component, title){
  var data = null;
  if(title === '公告'){
    data = this.state.data;
  }
  return <NavigatorIOS
    style={{flex:1}}
    barTintColor='#007AFF'
    titleTextColor="#FFF"
    tintColor="#FFF"
    translucent={false}
    initialRoute={{
      component: component,
      title: title,
      passProps:{
        data: data
      }
    }
    }/>;
},

render部分我没有修改路由部分

然后我想再请问一下，我在登陆界面输入了账号密码（随便写的）后，一直在loading界面，并没有进入主页或者提示密码错误，这是哪里的错误？

谢谢老师！

**Comment by xingweitian** [comment]
老师，由于我的疏忽，没有启动app.js，启动之后解决了第二个问题，但是warning依然存在，请老师解答

**Comment by vczero** [comment]
客气哈。

可以尝试理解这两句话：
1. Invalid prop 'initialRoute.component' of type 'object' supplied to 'NavigatorIOS', expected 'function' .
2.  Check the render method of 'myapp' .

如果没有解决，将你目前的代码发到我邮箱，：）

**Comment by xingweitian** [comment]
问题已解决，谢谢老师！
