### ISSUE TITLE
serve跑起来接口都是404报错

### ISSUE THREAD

**Issue by Chaunjie** [vczero/React-Native-App#9]
为什么serve跑起来接口都是404报错

**Comment by Mr7Cat** [comment]
同样的问题，手机端配置的是3000端口，ReloadJS后，终端提示

```
“GET /index.android.bundle?platform=android&dev=true 404 23.708 ms - 1453”
```

**Comment by vczero** [comment]
@Mr7Cat 这个目前不支持Android代码，可以跑下iOS。如果有兴趣，可以改造成Android，提个pull request, : )
至于服务端，可以把错误贴出来。

**Comment by vczero** [comment]
@xudao520 请贴出错误

**Comment by Chaunjie** [comment]
@vczero 
![3493603b-f758-4250-90b6-76812e89c2d0](https://cloud.githubusercontent.com/assets/12093709/15061486/b6a2b4ac-1368-11e6-82b6-3f6c143a895d.png)

**Comment by vczero** [comment]
@xudao520 
目前接口统一都是POST，不支持get请求:  
    app.post('/user/get', this.getUser);
    app.post('/user/create', this.addUser);
    app.post('/user/login', this.login);
    app.post('/user/login/token', this.loginByToken);
    app.post('/user/password/update', this.updatePassword);
    app.post('/user/delete', this.deleteUser);

比如：/user/get  post   需要提交两个字段信息：
var key = req.param('key');   //前后端沟通的密钥
var partment = req.param('partment');//部门

如果想了解服务：（1）可以在iOS跑整个应用 （2）可以查看server/routes/services下的接口

**Comment by Chaunjie** [comment]
好的谢谢 @vczero

**Comment by vczero** [comment]
@xudao520 小猫不错  ：）

**Comment by Chaunjie** [comment]
@vczero 貌似用的rn版本有点低，楼主准备什么时候更新到es6的写法？
